lobby-world: "world"
game-world-prefix: "w_expunge_"
gun:
  ladder-offset: 0.005
  jumping-offset: 0.05
  moving-offset: 0.005
  downed-offset: 0.25
director:
  spawn-radius: 8
  too-close-radius: 8
  depth: 2